# Generated by Django 3.2 on 2021-05-15 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('empty', 'empty'), ('c0', 'club0'), ('c1', 'club1'), ('c2', 'club2'), ('c3', 'club3'), ('c4', 'club4'), ('c5', 'club5'), ('c6', 'club6'), ('c7', 'club7'), ('c8', 'club8'), ('c9', 'club9')], default='empty', max_length=100)),
                ('budget', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Clubs',
            },
        ),
        migrations.CreateModel(
            name='entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('club', models.ManyToManyField(blank=True, to='api.club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('type', models.CharField(choices=[('club', 'Club'), ('entity', 'Entity')], max_length=10)),
                ('entity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.entity')),
            ],
        ),
    ]
