# Generated by Django 3.1.6 on 2021-04-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='club_name',
            field=models.CharField(choices=[('empty', 'empty'), ('c0', 'club0'), ('c1', 'club1'), ('c2', 'club2'), ('c3', 'club3'), ('c4', 'club4'), ('c5', 'club5'), ('c6', 'club6'), ('c7', 'club7'), ('c8', 'club8'), ('c9', 'club9')], default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(choices=[('empty', 'empty'), ('c0', 'club0'), ('c1', 'club1'), ('c2', 'club2'), ('c3', 'club3'), ('c4', 'club4'), ('c5', 'club5'), ('c6', 'club6'), ('c7', 'club7'), ('c8', 'club8'), ('c9', 'club9')], default='empty', max_length=100),
        ),
    ]
