# Generated by Django 3.1.6 on 2021-04-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210410_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(choices=[('c0', 'club0'), ('c1', 'club1'), ('c2', 'club2'), ('c3', 'club3'), ('c4', 'club4'), ('c5', 'club5'), ('c6', 'club6'), ('c7', 'club7'), ('c8', 'club8'), ('c9', 'club9')], max_length=100),
        ),
    ]
