# Generated by Django 3.2 on 2021-05-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='club',
        ),
        migrations.AddField(
            model_name='student',
            name='club',
            field=models.ManyToManyField(blank=True, to='api.club'),
        ),
    ]
