@json_type = application/json


POST {{APP_URL}}/login/ HTTP/1.1
Content-Type: application/json

{
    "username":"sushant19450@iiitd.ac.in",
    "password":"{{PASS}}"
}

###
POST {{AUTH_URL}}/token-auth/ HTTP/1.1
Content-Type: {{json_type}}

{
    "username":"sushant19450@iiitd.ac.in",
    "password":"{{PASS}}"
}