@json_type = application/json


POST {{app_url}}/login/ HTTP/1.1
Content-Type: application/json

{
    "username":"admin",
    "password":"{{pass}}"
}



###
POST {{auth_url}}/token-auth/ HTTP/1.1
Content-Type: application/json

{
    "username":"admin",
    "password":"{{pass}}"
}