# Generated by Django 3.1.6 on 2021-04-04 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0002_auto_20210404_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reimbursement.entity'),
        ),
    ]
