# Generated by Django 3.1.6 on 2021-04-04 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0003_payment_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reimbursement.entity'),
        ),
    ]
