# Generated by Django 3.1.6 on 2021-04-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0004_auto_20210404_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'Entities'},
        ),
        migrations.AddField(
            model_name='entity',
            name='boolean',
            field=models.BooleanField(default=False),
        ),
    ]
