# Generated by Django 3.1.6 on 2021-04-04 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0005_auto_20210404_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='boolean',
            new_name='club_access',
        ),
    ]
