# Generated by Django 3.1.6 on 2021-04-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0006_auto_20210404_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'permissions': [('club_access', 'Accessing Club Resources')], 'verbose_name_plural': 'Entities'},
        ),
        migrations.RemoveField(
            model_name='entity',
            name='club_access',
        ),
    ]
