# Generated by Django 3.1.7 on 2022-01-15 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211229_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='type',
            field=models.ForeignKey(default='Student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='api.type'),
        ),
    ]
